set(ENABLE_HIP ON CACHE BOOL "")

set(ROCM_VERSION "5.2.3" CACHE STRING "")
set(ROCM_PATH "/usr/tce/packages/rocmcc-tce/rocmcc-${ROCM_VERSION}" CACHE PATH "")
set(HIP_CLANG_INCLUDE_PATH "${ROCM_PATH}/include" CACHE PATH "")

set(CMAKE_C_COMPILER "${ROCM_PATH}/bin/amdclang" CACHE PATH "")
set(CMAKE_CXX_COMPILER "${ROCM_PATH}/bin/amdclang++" CACHE PATH "")
set(CMAKE_HIP_ARCHITECTURES "gfx90a" CACHE STRING "")

set(CHAI_ENABLE_MANAGED_PTR_ON_GPU OFF CACHE BOOL "")
