set(ENABLE_HIP ON CACHE BOOL "")

set(ROCM_VERSION "5.2.3" CACHE STRING "")
set(ROCM_PATH "/usr/tce/packages/rocmcc-tce/rocmcc-${ROCM_VERSION}" CACHE PATH "")
set(HIP_PATH "${ROCM_PATH}/hip" CACHE PATH "")
set(HIP_CLANG_INCLUDE_PATH "${ROCM_PATH}/include" CACHE PATH "")

set(CMAKE_C_COMPILER "${ROCM_PATH}/bin/amdclang" CACHE PATH "")
set(CMAKE_CXX_COMPILER "${ROCM_PATH}/bin/amdclang++" CACHE PATH "")
set(CMAKE_HIP_ARCHITECTURES "gfx90a" CACHE STRING "")
set(CMAKE_C_FLAGS "-fgpu-rdc" CACHE STRING "")
set(CMAKE_CXX_FLAGS "-fgpu-rdc" CACHE STRING "")
set(CMAKE_EXE_LINKER_FLAGS "-fuse-ld=lld -fgpu-rdc" CACHE STRING "")
set(CMAKE_HIP_LINK_FLAGS "-lroctx64 -fno-second-underscore" CACHE PATH "")
set(CMAKE_HIP_COMPILER_ID_RUN 1 CACHE BOOL "")
set(CMAKE_HIP_COMPILER_ROCM_ROOT ${ROCM_PATH} CACHE PATH "")

set(BLT_EXPORT_THIRDPARTY OFF CACHE BOOL "")
set(BLT_BUILD_HIP_WITH_HIPCC TRUE CACHE BOOL "")

set(CHAI_ENABLE_MANAGED_PTR_ON_GPU OFF CACHE BOOL "")
