set(COMPILER_BASE "/usr/tce/packages/rocmcc-tce/rocmcc-5.2.3/bin" CACHE PATH "")
set(CMAKE_C_COMPILER "${COMPILER_BASE}/amdclang" CACHE PATH "")
set(CMAKE_CXX_COMPILER "${COMPILER_BASE}/amdclang++" CACHE PATH "")

set(ROCM_PATH "/usr/tce/packages/rocmcc-tce/rocmcc-${ROCM_VERSION}" CACHE PATH "")
set(HIP_PATH "${ROCM_PATH}/hip" CACHE PATH "")
set(HIP_CLANG_INCLUDE_PATH "${ROCM_PATH}/include" CACHE PATH "")
set(CMAKE_HIP_ARCHITECTURES "gfx90a" CACHE STRING "")
set(CMAKE_HIP_COMPILER_ID_RUN 1 CACHE BOOL "")
set(CMAKE_HIP_COMPILER_ROCM_ROOT ${ROCM_PATH} CACHE PATH "")

set(CHAI_ENABLE_MANAGED_PTR_ON_GPU OFF CACHE BOOL "")
