name: C/C++ CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: init submodules
      run: git submodule update --init
    - name: build directory
      run: mkdir build && cd build
    - name: cmake
      run: cmake ../
    - name: make
      run: make
    - name: make test
      run: make test
