name: C/C++ CI

on:
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: init submodules
      run: git submodule update --init
    - name: build directory
      run: mkdir build
    - name: cmake
      run: cmake ../
      working_directory: build
    - name: make
      run: make -j
      working-directory: build
    - name: make test
      run: make test
      working-directory: build
