name: C/C++ CI

on:
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Initialize submodules
      run: git submodule update --init
    - name: Make build directory
      run: mkdir build
    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v1.13.1
      with:
        cmake-version: '3.18.x'
    - name: Run CMake
      run: cmake ../ -DCMAKE_BUILD_TYPE=Debug
      working-directory: build
    - name: Run make
      run: make -j
      working-directory: build
    - name: Run tests
      run: make test CTEST_OUTPUT_ON_FAILURE=TRUE
      working-directory: build
    - name: Clean up
      run: rm -rf build
